Revert "Clean up call composer call code"
Fixes an error where a user tries to hang up a VOLTE or Wifi Call the screen dialer ui gets stuck at disconnecting and the call doesn't get disconnected until a reboot is performed.

E AndroidRuntime: java.lang.NoSuchMethodError: No static method buildCallComposerToken(II)Ljava/lang/String; in class Lorg/codeaurora/ims/utils/CallComposerInfoUtils; or its super classes (declaration of 'org.codeaurora.ims.utils.CallComposerInfoUtils' appears in /product/framework/ims-ext-common.jar)

Tested successfully on Pixel 4a aka sunfish.

This reverts commit f726fed2aa1e5b430c5071e733c725087f9919bc.

Change-Id: I889176ab59971833e26eb81cad26f155674a2d65